services:
  portfolio:
    image: portfolio:latest
    container_name: portfolio
    platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - ./.env
    restart: unless-stopped